package src;


//import com.sun.jdi.connect.spi.Connection;
//import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.event.DocumentListener;
import java.sql.ResultSet;




public class signupinterface extends javax.swing.JFrame {

    /**
     * Creates new form signupinterface
     */
    public signupinterface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtnom = new javax.swing.JTextField();
        txtadr = new javax.swing.JTextField();
        txtemail = new javax.swing.JTextField();
        txttel = new javax.swing.JTextField();
        txtprenom = new javax.swing.JTextField();
        txtmdp = new javax.swing.JPasswordField();
        btnsave = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Footlight MT Light", 2, 24)); // NOI18N
        jLabel2.setText("Nom");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, 80, 30));

        jLabel3.setFont(new java.awt.Font("Footlight MT Light", 2, 24)); // NOI18N
        jLabel3.setText("Prénom");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, 120, 30));

        jLabel4.setFont(new java.awt.Font("Footlight MT Light", 2, 24)); // NOI18N
        jLabel4.setText("Adresse");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 380, 90, 30));

        jLabel5.setFont(new java.awt.Font("Footlight MT Light", 2, 24)); // NOI18N
        jLabel5.setText("Email");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 430, 80, 30));

        jLabel6.setFont(new java.awt.Font("Footlight MT Light", 2, 24)); // NOI18N
        jLabel6.setText("Tél");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 480, 80, 30));

        jLabel7.setFont(new java.awt.Font("Footlight MT Light", 2, 24)); // NOI18N
        jLabel7.setText("Mot de passe ");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 530, 180, 30));

        txtnom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnomActionPerformed(evt);
            }
        });
        getContentPane().add(txtnom, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 280, 251, -1));

        txtadr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtadrActionPerformed(evt);
            }
        });
        getContentPane().add(txtadr, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 380, 251, -1));

        txtemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtemailActionPerformed(evt);
            }
        });
        getContentPane().add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 430, 251, -1));

        txttel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttelActionPerformed(evt);
            }
        });
        getContentPane().add(txttel, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 480, 251, -1));

        txtprenom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtprenomActionPerformed(evt);
            }
        });
        getContentPane().add(txtprenom, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 330, 251, -1));
        getContentPane().add(txtmdp, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 530, 251, -1));

        btnsave.setFont(new java.awt.Font("Footlight MT Light", 2, 20)); // NOI18N
        btnsave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/enregistrer.png"))); // NOI18N
        btnsave.setText("Enregistrer");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnsave, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 600, -1, -1));

        jButton2.setFont(new java.awt.Font("Footlight MT Light", 2, 20)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit.png"))); // NOI18N
        jButton2.setText("Reculer");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 600, 160, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/signuppage.png"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtprenomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtprenomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtprenomActionPerformed

    private void txtnomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnomActionPerformed

    private void txtadrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtadrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtadrActionPerformed

    private void txtemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtemailActionPerformed

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
    String nom = txtnom.getText().trim();
    String prenom = txtprenom.getText().trim();
    String adresse = txtadr.getText().trim();
    String email = txtemail.getText().trim();
    String tel = txttel.getText().trim();
    String motDePasse = new String(txtmdp.getPassword());

        // VALIDATION SECTION
    if (!nom.matches("[a-zA-Z]+$")) {
        JOptionPane.showMessageDialog(this, "Nom doit contenir uniquement des lettres.");
        return;
    }

    if (!prenom.matches("[a-zA-Z]+$")) {
        JOptionPane.showMessageDialog(this, "Prénom doit contenir uniquement des lettres.");
        return;
    }

    if (!email.contains("@")) {
        JOptionPane.showMessageDialog(this, "Email invalide. Il doit être sous la forme 'exemple@email.com'.");
        return;
    }

    if (!tel.matches("^[259]\\d{7}$")) {
        JOptionPane.showMessageDialog(this, "Téléphone invalide. Il doit contenir 8 chiffres et commencer par 2, 5 ou 9.");
        return;
    }

    if (motDePasse.length() < 8) {
        JOptionPane.showMessageDialog(this, "Mot de passe trop court. Minimum 8 caractères.");
        return;
    }
    
     if (emailExists(email)) {
        JOptionPane.showMessageDialog(this, "Cet email est déjà utilisé. Veuillez en choisir un autre.");
        return;
    }
    
    try {
        // Load the JDBC driver (for Oracle, use: oracle.jdbc.OracleDriver)
        Class.forName("oracle.jdbc.OracleDriver");

             // Prepare SQL statement
             try ( // Connect to the database
                     Connection con = DriverManager.getConnection(
                              "jdbc:oracle:thin:@localhost:1521/orcl", "sys as sysdba", "maha13")) {
                 // Prepare SQL statement
                 String query = "INSERT INTO clients (nom, prenom, adresse, email, tel, mdp) VALUES (?, ?, ?, ?, ?, ?)";
                 PreparedStatement pst = con.prepareStatement(query);
                 
                 pst.setString(1, nom);
                 pst.setString(2, prenom);
                 pst.setString(3, adresse);
                 pst.setString(4, email);
                 pst.setString(5, tel);
                 pst.setString(6, motDePasse);
                 
                 // Execute update
                 pst.executeUpdate();
                 
                 JOptionPane.showMessageDialog(this, "Inscription réussie!");
                txtnom.setText("");
                txtprenom.setText("");
                txtadr.setText("");
                txtmdp.setText("");
                txttel.setText("");
                txtemail.setText("");
                 
                 pst.close();
             }

    } catch (ClassNotFoundException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Erreur lors de l'inscription: " + e.getMessage());
    } catch (SQLException ex) {
            Logger.getLogger(signupinterface.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnsaveActionPerformed

    private boolean emailExists(String email) {
    boolean exists = false;
    try {
        Connection con = DriverManager.getConnection(
            "jdbc:oracle:thin:@//localhost:1521/XEPDB1", "HR", "hr");
        String query = "SELECT COUNT(*) FROM clients WHERE email = ?";
        PreparedStatement pst = con.prepareStatement(query);
        pst.setString(1, email);
        ResultSet rs = pst.executeQuery();
        if (rs.next()) {
            exists = rs.getInt(1) > 0;
        }
        rs.close();
        pst.close();
        con.close();
    } catch (SQLException ex) {
        ex.printStackTrace();
    }
    return exists;
}

    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new welcomeinterface().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txttelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttelActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(signupinterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(signupinterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(signupinterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(signupinterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new signupinterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnsave;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtadr;
    private javax.swing.JTextField txtemail;
    private javax.swing.JPasswordField txtmdp;
    private javax.swing.JTextField txtnom;
    private javax.swing.JTextField txtprenom;
    private javax.swing.JTextField txttel;
    // End of variables declaration//GEN-END:variables
}
